/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingTestimonialsRouteImport } from './routes/_marketing.testimonials'
import { Route as MarketingServicesRouteImport } from './routes/_marketing.services'
import { Route as MarketingQuoteRouteImport } from './routes/_marketing.quote'
import { Route as MarketingProjectsRouteImport } from './routes/_marketing.projects'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingCareersRouteImport } from './routes/_marketing.careers'
import { Route as MarketingBlogRouteImport } from './routes/_marketing.blog'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedStaffRouteRouteImport } from './routes/_authenticated/staff/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as MarketingServicesSolarRouteImport } from './routes/_marketing.services.solar'
import { Route as MarketingServicesRealEstateRouteImport } from './routes/_marketing.services.real-estate'
import { Route as MarketingServicesInteriorsRouteImport } from './routes/_marketing.services.interiors'
import { Route as MarketingServicesHvacRouteImport } from './routes/_marketing.services.hvac'
import { Route as MarketingServicesConstructionRouteImport } from './routes/_marketing.services.construction'
import { Route as AuthenticatedStaffLeavesRouteImport } from './routes/_authenticated/staff/leaves'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminQuotesRouteImport } from './routes/_authenticated/admin/quotes'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin/projects'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminHrRouteImport } from './routes/_authenticated/admin/hr'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin/blog'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTestimonialsRoute = MarketingTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingServicesRoute = MarketingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingQuoteRoute = MarketingQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingProjectsRoute = MarketingProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCareersRoute = MarketingCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogRoute = MarketingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRouteRoute = AuthenticatedStaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const MarketingServicesSolarRoute = MarketingServicesSolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => MarketingServicesRoute,
} as any)
const MarketingServicesRealEstateRoute =
  MarketingServicesRealEstateRouteImport.update({
    id: '/real-estate',
    path: '/real-estate',
    getParentRoute: () => MarketingServicesRoute,
  } as any)
const MarketingServicesInteriorsRoute =
  MarketingServicesInteriorsRouteImport.update({
    id: '/interiors',
    path: '/interiors',
    getParentRoute: () => MarketingServicesRoute,
  } as any)
const MarketingServicesHvacRoute = MarketingServicesHvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => MarketingServicesRoute,
} as any)
const MarketingServicesConstructionRoute =
  MarketingServicesConstructionRouteImport.update({
    id: '/construction',
    path: '/construction',
    getParentRoute: () => MarketingServicesRoute,
  } as any)
const AuthenticatedStaffLeavesRoute =
  AuthenticatedStaffLeavesRouteImport.update({
    id: '/leaves',
    path: '/leaves',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminQuotesRoute =
  AuthenticatedAdminQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminHrRoute = AuthenticatedAdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/about': typeof MarketingAboutRoute
  '/blog': typeof MarketingBlogRoute
  '/careers': typeof MarketingCareersRoute
  '/contact': typeof MarketingContactRoute
  '/projects': typeof MarketingProjectsRoute
  '/quote': typeof MarketingQuoteRoute
  '/services': typeof MarketingServicesRouteWithChildren
  '/testimonials': typeof MarketingTestimonialsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/hr': typeof AuthenticatedAdminHrRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/staff/leaves': typeof AuthenticatedStaffLeavesRoute
  '/services/construction': typeof MarketingServicesConstructionRoute
  '/services/hvac': typeof MarketingServicesHvacRoute
  '/services/interiors': typeof MarketingServicesInteriorsRoute
  '/services/real-estate': typeof MarketingServicesRealEstateRoute
  '/services/solar': typeof MarketingServicesSolarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/about': typeof MarketingAboutRoute
  '/blog': typeof MarketingBlogRoute
  '/careers': typeof MarketingCareersRoute
  '/contact': typeof MarketingContactRoute
  '/projects': typeof MarketingProjectsRoute
  '/quote': typeof MarketingQuoteRoute
  '/services': typeof MarketingServicesRouteWithChildren
  '/testimonials': typeof MarketingTestimonialsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/hr': typeof AuthenticatedAdminHrRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/staff/leaves': typeof AuthenticatedStaffLeavesRoute
  '/services/construction': typeof MarketingServicesConstructionRoute
  '/services/hvac': typeof MarketingServicesHvacRoute
  '/services/interiors': typeof MarketingServicesInteriorsRoute
  '/services/real-estate': typeof MarketingServicesRealEstateRoute
  '/services/solar': typeof MarketingServicesSolarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/blog': typeof MarketingBlogRoute
  '/_marketing/careers': typeof MarketingCareersRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/projects': typeof MarketingProjectsRoute
  '/_marketing/quote': typeof MarketingQuoteRoute
  '/_marketing/services': typeof MarketingServicesRouteWithChildren
  '/_marketing/testimonials': typeof MarketingTestimonialsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/hr': typeof AuthenticatedAdminHrRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/staff/leaves': typeof AuthenticatedStaffLeavesRoute
  '/_marketing/services/construction': typeof MarketingServicesConstructionRoute
  '/_marketing/services/hvac': typeof MarketingServicesHvacRoute
  '/_marketing/services/interiors': typeof MarketingServicesInteriorsRoute
  '/_marketing/services/real-estate': typeof MarketingServicesRealEstateRoute
  '/_marketing/services/solar': typeof MarketingServicesSolarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/staff'
    | '/portal'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/projects'
    | '/quote'
    | '/services'
    | '/testimonials'
    | '/admin/blog'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/tickets'
    | '/staff/leaves'
    | '/services/construction'
    | '/services/hvac'
    | '/services/interiors'
    | '/services/real-estate'
    | '/services/solar'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/projects'
    | '/quote'
    | '/services'
    | '/testimonials'
    | '/admin/blog'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/messages'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/tickets'
    | '/staff/leaves'
    | '/services/construction'
    | '/services/hvac'
    | '/services/interiors'
    | '/services/real-estate'
    | '/services/solar'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_marketing'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/staff'
    | '/_authenticated/portal'
    | '/_marketing/about'
    | '/_marketing/blog'
    | '/_marketing/careers'
    | '/_marketing/contact'
    | '/_marketing/projects'
    | '/_marketing/quote'
    | '/_marketing/services'
    | '/_marketing/testimonials'
    | '/_marketing/'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/hr'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/quotes'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/staff/leaves'
    | '/_marketing/services/construction'
    | '/_marketing/services/hvac'
    | '/_marketing/services/interiors'
    | '/_marketing/services/real-estate'
    | '/_marketing/services/solar'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/testimonials': {
      id: '/_marketing/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof MarketingTestimonialsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/services': {
      id: '/_marketing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MarketingServicesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/quote': {
      id: '/_marketing/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof MarketingQuoteRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/projects': {
      id: '/_marketing/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MarketingProjectsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/careers': {
      id: '/_marketing/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof MarketingCareersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog': {
      id: '/_marketing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof MarketingBlogRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_marketing/services/solar': {
      id: '/_marketing/services/solar'
      path: '/solar'
      fullPath: '/services/solar'
      preLoaderRoute: typeof MarketingServicesSolarRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/real-estate': {
      id: '/_marketing/services/real-estate'
      path: '/real-estate'
      fullPath: '/services/real-estate'
      preLoaderRoute: typeof MarketingServicesRealEstateRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/interiors': {
      id: '/_marketing/services/interiors'
      path: '/interiors'
      fullPath: '/services/interiors'
      preLoaderRoute: typeof MarketingServicesInteriorsRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/hvac': {
      id: '/_marketing/services/hvac'
      path: '/hvac'
      fullPath: '/services/hvac'
      preLoaderRoute: typeof MarketingServicesHvacRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/construction': {
      id: '/_marketing/services/construction'
      path: '/construction'
      fullPath: '/services/construction'
      preLoaderRoute: typeof MarketingServicesConstructionRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_authenticated/staff/leaves': {
      id: '/_authenticated/staff/leaves'
      path: '/leaves'
      fullPath: '/staff/leaves'
      preLoaderRoute: typeof AuthenticatedStaffLeavesRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quotes': {
      id: '/_authenticated/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthenticatedAdminQuotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hr': {
      id: '/_authenticated/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AuthenticatedAdminHrRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminHrRoute: typeof AuthenticatedAdminHrRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminQuotesRoute: typeof AuthenticatedAdminQuotesRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
    AuthenticatedAdminHrRoute: AuthenticatedAdminHrRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
    AuthenticatedAdminQuotesRoute: AuthenticatedAdminQuotesRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedStaffRouteRouteChildren {
  AuthenticatedStaffLeavesRoute: typeof AuthenticatedStaffLeavesRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteRouteChildren: AuthenticatedStaffRouteRouteChildren =
  {
    AuthenticatedStaffLeavesRoute: AuthenticatedStaffLeavesRoute,
    AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  }

const AuthenticatedStaffRouteRouteWithChildren =
  AuthenticatedStaffRouteRoute._addFileChildren(
    AuthenticatedStaffRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedStaffRouteRoute: typeof AuthenticatedStaffRouteRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedStaffRouteRoute: AuthenticatedStaffRouteRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketingServicesRouteChildren {
  MarketingServicesConstructionRoute: typeof MarketingServicesConstructionRoute
  MarketingServicesHvacRoute: typeof MarketingServicesHvacRoute
  MarketingServicesInteriorsRoute: typeof MarketingServicesInteriorsRoute
  MarketingServicesRealEstateRoute: typeof MarketingServicesRealEstateRoute
  MarketingServicesSolarRoute: typeof MarketingServicesSolarRoute
}

const MarketingServicesRouteChildren: MarketingServicesRouteChildren = {
  MarketingServicesConstructionRoute: MarketingServicesConstructionRoute,
  MarketingServicesHvacRoute: MarketingServicesHvacRoute,
  MarketingServicesInteriorsRoute: MarketingServicesInteriorsRoute,
  MarketingServicesRealEstateRoute: MarketingServicesRealEstateRoute,
  MarketingServicesSolarRoute: MarketingServicesSolarRoute,
}

const MarketingServicesRouteWithChildren =
  MarketingServicesRoute._addFileChildren(MarketingServicesRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingBlogRoute: typeof MarketingBlogRoute
  MarketingCareersRoute: typeof MarketingCareersRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingProjectsRoute: typeof MarketingProjectsRoute
  MarketingQuoteRoute: typeof MarketingQuoteRoute
  MarketingServicesRoute: typeof MarketingServicesRouteWithChildren
  MarketingTestimonialsRoute: typeof MarketingTestimonialsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingBlogRoute: MarketingBlogRoute,
  MarketingCareersRoute: MarketingCareersRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingProjectsRoute: MarketingProjectsRoute,
  MarketingQuoteRoute: MarketingQuoteRoute,
  MarketingServicesRoute: MarketingServicesRouteWithChildren,
  MarketingTestimonialsRoute: MarketingTestimonialsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
