/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingTestimonialsRouteImport } from './routes/_marketing.testimonials'
import { Route as MarketingServicesRouteImport } from './routes/_marketing.services'
import { Route as MarketingQuoteRouteImport } from './routes/_marketing.quote'
import { Route as MarketingProjectsRouteImport } from './routes/_marketing.projects'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingCareersRouteImport } from './routes/_marketing.careers'
import { Route as MarketingBlogRouteImport } from './routes/_marketing.blog'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedStaffRouteRouteImport } from './routes/_authenticated/staff/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing.blog.index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as MarketingServicesSolarRouteImport } from './routes/_marketing.services.solar'
import { Route as MarketingServicesRealEstateRouteImport } from './routes/_marketing.services.real-estate'
import { Route as MarketingServicesInteriorsRouteImport } from './routes/_marketing.services.interiors'
import { Route as MarketingServicesHvacRouteImport } from './routes/_marketing.services.hvac'
import { Route as MarketingServicesConstructionRouteImport } from './routes/_marketing.services.construction'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing.blog.$slug'
import { Route as AuthenticatedStaffLeavesRouteImport } from './routes/_authenticated/staff/leaves'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin/vendors'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin/system'
import { Route as AuthenticatedAdminSiteMonitoringRouteImport } from './routes/_authenticated/admin/site-monitoring'
import { Route as AuthenticatedAdminSchedulingRouteImport } from './routes/_authenticated/admin/scheduling'
import { Route as AuthenticatedAdminSafetyRouteImport } from './routes/_authenticated/admin/safety'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminQuotesRouteImport } from './routes/_authenticated/admin/quotes'
import { Route as AuthenticatedAdminQualityRouteImport } from './routes/_authenticated/admin/quality'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin/projects'
import { Route as AuthenticatedAdminProcurementRouteImport } from './routes/_authenticated/admin/procurement'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminMaterialsRouteImport } from './routes/_authenticated/admin/materials'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminHrRouteImport } from './routes/_authenticated/admin/hr'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminEquipmentRouteImport } from './routes/_authenticated/admin/equipment'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin/employees'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin/blog'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTestimonialsRoute = MarketingTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingServicesRoute = MarketingServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingQuoteRoute = MarketingQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingProjectsRoute = MarketingProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCareersRoute = MarketingCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogRoute = MarketingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRouteRoute = AuthenticatedStaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingBlogRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const MarketingServicesSolarRoute = MarketingServicesSolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => MarketingServicesRoute,
} as any)
const MarketingServicesRealEstateRoute =
  MarketingServicesRealEstateRouteImport.update({
    id: '/real-estate',
    path: '/real-estate',
    getParentRoute: () => MarketingServicesRoute,
  } as any)
const MarketingServicesInteriorsRoute =
  MarketingServicesInteriorsRouteImport.update({
    id: '/interiors',
    path: '/interiors',
    getParentRoute: () => MarketingServicesRoute,
  } as any)
const MarketingServicesHvacRoute = MarketingServicesHvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => MarketingServicesRoute,
} as any)
const MarketingServicesConstructionRoute =
  MarketingServicesConstructionRouteImport.update({
    id: '/construction',
    path: '/construction',
    getParentRoute: () => MarketingServicesRoute,
  } as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingBlogRoute,
} as any)
const AuthenticatedStaffLeavesRoute =
  AuthenticatedStaffLeavesRouteImport.update({
    id: '/leaves',
    path: '/leaves',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSiteMonitoringRoute =
  AuthenticatedAdminSiteMonitoringRouteImport.update({
    id: '/site-monitoring',
    path: '/site-monitoring',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSchedulingRoute =
  AuthenticatedAdminSchedulingRouteImport.update({
    id: '/scheduling',
    path: '/scheduling',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSafetyRoute =
  AuthenticatedAdminSafetyRouteImport.update({
    id: '/safety',
    path: '/safety',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuotesRoute =
  AuthenticatedAdminQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQualityRoute =
  AuthenticatedAdminQualityRouteImport.update({
    id: '/quality',
    path: '/quality',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProcurementRoute =
  AuthenticatedAdminProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMaterialsRoute =
  AuthenticatedAdminMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminHrRoute = AuthenticatedAdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEquipmentRoute =
  AuthenticatedAdminEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/about': typeof MarketingAboutRoute
  '/blog': typeof MarketingBlogRouteWithChildren
  '/careers': typeof MarketingCareersRoute
  '/contact': typeof MarketingContactRoute
  '/projects': typeof MarketingProjectsRoute
  '/quote': typeof MarketingQuoteRoute
  '/services': typeof MarketingServicesRouteWithChildren
  '/testimonials': typeof MarketingTestimonialsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/hr': typeof AuthenticatedAdminHrRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/procurement': typeof AuthenticatedAdminProcurementRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/admin/scheduling': typeof AuthenticatedAdminSchedulingRoute
  '/admin/site-monitoring': typeof AuthenticatedAdminSiteMonitoringRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/staff/leaves': typeof AuthenticatedStaffLeavesRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/services/construction': typeof MarketingServicesConstructionRoute
  '/services/hvac': typeof MarketingServicesHvacRoute
  '/services/interiors': typeof MarketingServicesInteriorsRoute
  '/services/real-estate': typeof MarketingServicesRealEstateRoute
  '/services/solar': typeof MarketingServicesSolarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/blog/': typeof MarketingBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/about': typeof MarketingAboutRoute
  '/careers': typeof MarketingCareersRoute
  '/contact': typeof MarketingContactRoute
  '/projects': typeof MarketingProjectsRoute
  '/quote': typeof MarketingQuoteRoute
  '/services': typeof MarketingServicesRouteWithChildren
  '/testimonials': typeof MarketingTestimonialsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/hr': typeof AuthenticatedAdminHrRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/procurement': typeof AuthenticatedAdminProcurementRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/admin/scheduling': typeof AuthenticatedAdminSchedulingRoute
  '/admin/site-monitoring': typeof AuthenticatedAdminSiteMonitoringRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/staff/leaves': typeof AuthenticatedStaffLeavesRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/services/construction': typeof MarketingServicesConstructionRoute
  '/services/hvac': typeof MarketingServicesHvacRoute
  '/services/interiors': typeof MarketingServicesInteriorsRoute
  '/services/real-estate': typeof MarketingServicesRealEstateRoute
  '/services/solar': typeof MarketingServicesSolarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/blog': typeof MarketingBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/blog': typeof MarketingBlogRouteWithChildren
  '/_marketing/careers': typeof MarketingCareersRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/projects': typeof MarketingProjectsRoute
  '/_marketing/quote': typeof MarketingQuoteRoute
  '/_marketing/services': typeof MarketingServicesRouteWithChildren
  '/_marketing/testimonials': typeof MarketingTestimonialsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/equipment': typeof AuthenticatedAdminEquipmentRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/hr': typeof AuthenticatedAdminHrRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/materials': typeof AuthenticatedAdminMaterialsRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/procurement': typeof AuthenticatedAdminProcurementRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/quality': typeof AuthenticatedAdminQualityRoute
  '/_authenticated/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/safety': typeof AuthenticatedAdminSafetyRoute
  '/_authenticated/admin/scheduling': typeof AuthenticatedAdminSchedulingRoute
  '/_authenticated/admin/site-monitoring': typeof AuthenticatedAdminSiteMonitoringRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/staff/leaves': typeof AuthenticatedStaffLeavesRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/services/construction': typeof MarketingServicesConstructionRoute
  '/_marketing/services/hvac': typeof MarketingServicesHvacRoute
  '/_marketing/services/interiors': typeof MarketingServicesInteriorsRoute
  '/_marketing/services/real-estate': typeof MarketingServicesRealEstateRoute
  '/_marketing/services/solar': typeof MarketingServicesSolarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/staff'
    | '/portal'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/projects'
    | '/quote'
    | '/services'
    | '/testimonials'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/equipment'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/materials'
    | '/admin/messages'
    | '/admin/permissions'
    | '/admin/procurement'
    | '/admin/projects'
    | '/admin/quality'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/safety'
    | '/admin/scheduling'
    | '/admin/site-monitoring'
    | '/admin/system'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vendors'
    | '/staff/leaves'
    | '/blog/$slug'
    | '/services/construction'
    | '/services/hvac'
    | '/services/interiors'
    | '/services/real-estate'
    | '/services/solar'
    | '/admin/'
    | '/staff/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/about'
    | '/careers'
    | '/contact'
    | '/projects'
    | '/quote'
    | '/services'
    | '/testimonials'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/clients'
    | '/admin/documents'
    | '/admin/employees'
    | '/admin/equipment'
    | '/admin/finance'
    | '/admin/hr'
    | '/admin/leads'
    | '/admin/materials'
    | '/admin/messages'
    | '/admin/permissions'
    | '/admin/procurement'
    | '/admin/projects'
    | '/admin/quality'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/safety'
    | '/admin/scheduling'
    | '/admin/site-monitoring'
    | '/admin/system'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/vendors'
    | '/staff/leaves'
    | '/blog/$slug'
    | '/services/construction'
    | '/services/hvac'
    | '/services/interiors'
    | '/services/real-estate'
    | '/services/solar'
    | '/admin'
    | '/staff'
    | '/blog'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_marketing'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/staff'
    | '/_authenticated/portal'
    | '/_marketing/about'
    | '/_marketing/blog'
    | '/_marketing/careers'
    | '/_marketing/contact'
    | '/_marketing/projects'
    | '/_marketing/quote'
    | '/_marketing/services'
    | '/_marketing/testimonials'
    | '/_marketing/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/equipment'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/hr'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/materials'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/procurement'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/quality'
    | '/_authenticated/admin/quotes'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/safety'
    | '/_authenticated/admin/scheduling'
    | '/_authenticated/admin/site-monitoring'
    | '/_authenticated/admin/system'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/staff/leaves'
    | '/_marketing/blog/$slug'
    | '/_marketing/services/construction'
    | '/_marketing/services/hvac'
    | '/_marketing/services/interiors'
    | '/_marketing/services/real-estate'
    | '/_marketing/services/solar'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
    | '/_marketing/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/testimonials': {
      id: '/_marketing/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof MarketingTestimonialsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/services': {
      id: '/_marketing/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof MarketingServicesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/quote': {
      id: '/_marketing/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof MarketingQuoteRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/projects': {
      id: '/_marketing/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MarketingProjectsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/careers': {
      id: '/_marketing/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof MarketingCareersRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog': {
      id: '/_marketing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof MarketingBlogRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingBlogRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_marketing/services/solar': {
      id: '/_marketing/services/solar'
      path: '/solar'
      fullPath: '/services/solar'
      preLoaderRoute: typeof MarketingServicesSolarRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/real-estate': {
      id: '/_marketing/services/real-estate'
      path: '/real-estate'
      fullPath: '/services/real-estate'
      preLoaderRoute: typeof MarketingServicesRealEstateRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/interiors': {
      id: '/_marketing/services/interiors'
      path: '/interiors'
      fullPath: '/services/interiors'
      preLoaderRoute: typeof MarketingServicesInteriorsRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/hvac': {
      id: '/_marketing/services/hvac'
      path: '/hvac'
      fullPath: '/services/hvac'
      preLoaderRoute: typeof MarketingServicesHvacRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/services/construction': {
      id: '/_marketing/services/construction'
      path: '/construction'
      fullPath: '/services/construction'
      preLoaderRoute: typeof MarketingServicesConstructionRouteImport
      parentRoute: typeof MarketingServicesRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingBlogRoute
    }
    '/_authenticated/staff/leaves': {
      id: '/_authenticated/staff/leaves'
      path: '/leaves'
      fullPath: '/staff/leaves'
      preLoaderRoute: typeof AuthenticatedStaffLeavesRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/site-monitoring': {
      id: '/_authenticated/admin/site-monitoring'
      path: '/site-monitoring'
      fullPath: '/admin/site-monitoring'
      preLoaderRoute: typeof AuthenticatedAdminSiteMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/scheduling': {
      id: '/_authenticated/admin/scheduling'
      path: '/scheduling'
      fullPath: '/admin/scheduling'
      preLoaderRoute: typeof AuthenticatedAdminSchedulingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/safety': {
      id: '/_authenticated/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AuthenticatedAdminSafetyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quotes': {
      id: '/_authenticated/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthenticatedAdminQuotesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quality': {
      id: '/_authenticated/admin/quality'
      path: '/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AuthenticatedAdminQualityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/procurement': {
      id: '/_authenticated/admin/procurement'
      path: '/procurement'
      fullPath: '/admin/procurement'
      preLoaderRoute: typeof AuthenticatedAdminProcurementRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/materials': {
      id: '/_authenticated/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AuthenticatedAdminMaterialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hr': {
      id: '/_authenticated/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AuthenticatedAdminHrRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/equipment': {
      id: '/_authenticated/admin/equipment'
      path: '/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AuthenticatedAdminEquipmentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminEquipmentRoute: typeof AuthenticatedAdminEquipmentRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminHrRoute: typeof AuthenticatedAdminHrRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMaterialsRoute: typeof AuthenticatedAdminMaterialsRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminProcurementRoute: typeof AuthenticatedAdminProcurementRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminQualityRoute: typeof AuthenticatedAdminQualityRoute
  AuthenticatedAdminQuotesRoute: typeof AuthenticatedAdminQuotesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSafetyRoute: typeof AuthenticatedAdminSafetyRoute
  AuthenticatedAdminSchedulingRoute: typeof AuthenticatedAdminSchedulingRoute
  AuthenticatedAdminSiteMonitoringRoute: typeof AuthenticatedAdminSiteMonitoringRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
    AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
    AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
    AuthenticatedAdminEquipmentRoute: AuthenticatedAdminEquipmentRoute,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminHrRoute: AuthenticatedAdminHrRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminMaterialsRoute: AuthenticatedAdminMaterialsRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
    AuthenticatedAdminProcurementRoute: AuthenticatedAdminProcurementRoute,
    AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
    AuthenticatedAdminQualityRoute: AuthenticatedAdminQualityRoute,
    AuthenticatedAdminQuotesRoute: AuthenticatedAdminQuotesRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSafetyRoute: AuthenticatedAdminSafetyRoute,
    AuthenticatedAdminSchedulingRoute: AuthenticatedAdminSchedulingRoute,
    AuthenticatedAdminSiteMonitoringRoute:
      AuthenticatedAdminSiteMonitoringRoute,
    AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedStaffRouteRouteChildren {
  AuthenticatedStaffLeavesRoute: typeof AuthenticatedStaffLeavesRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteRouteChildren: AuthenticatedStaffRouteRouteChildren =
  {
    AuthenticatedStaffLeavesRoute: AuthenticatedStaffLeavesRoute,
    AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  }

const AuthenticatedStaffRouteRouteWithChildren =
  AuthenticatedStaffRouteRoute._addFileChildren(
    AuthenticatedStaffRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedStaffRouteRoute: typeof AuthenticatedStaffRouteRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedStaffRouteRoute: AuthenticatedStaffRouteRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketingBlogRouteChildren {
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
}

const MarketingBlogRouteChildren: MarketingBlogRouteChildren = {
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
}

const MarketingBlogRouteWithChildren = MarketingBlogRoute._addFileChildren(
  MarketingBlogRouteChildren,
)

interface MarketingServicesRouteChildren {
  MarketingServicesConstructionRoute: typeof MarketingServicesConstructionRoute
  MarketingServicesHvacRoute: typeof MarketingServicesHvacRoute
  MarketingServicesInteriorsRoute: typeof MarketingServicesInteriorsRoute
  MarketingServicesRealEstateRoute: typeof MarketingServicesRealEstateRoute
  MarketingServicesSolarRoute: typeof MarketingServicesSolarRoute
}

const MarketingServicesRouteChildren: MarketingServicesRouteChildren = {
  MarketingServicesConstructionRoute: MarketingServicesConstructionRoute,
  MarketingServicesHvacRoute: MarketingServicesHvacRoute,
  MarketingServicesInteriorsRoute: MarketingServicesInteriorsRoute,
  MarketingServicesRealEstateRoute: MarketingServicesRealEstateRoute,
  MarketingServicesSolarRoute: MarketingServicesSolarRoute,
}

const MarketingServicesRouteWithChildren =
  MarketingServicesRoute._addFileChildren(MarketingServicesRouteChildren)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingBlogRoute: typeof MarketingBlogRouteWithChildren
  MarketingCareersRoute: typeof MarketingCareersRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingProjectsRoute: typeof MarketingProjectsRoute
  MarketingQuoteRoute: typeof MarketingQuoteRoute
  MarketingServicesRoute: typeof MarketingServicesRouteWithChildren
  MarketingTestimonialsRoute: typeof MarketingTestimonialsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingBlogRoute: MarketingBlogRouteWithChildren,
  MarketingCareersRoute: MarketingCareersRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingProjectsRoute: MarketingProjectsRoute,
  MarketingQuoteRoute: MarketingQuoteRoute,
  MarketingServicesRoute: MarketingServicesRouteWithChildren,
  MarketingTestimonialsRoute: MarketingTestimonialsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
